### ISSUE TITLE
damerau_levenshtein.c segfault

### ISSUE THREAD

**Issue by tsellon** [jamesturk/jellyfish#52]
First off, thanks for the library! It's been great.

Now the issue--
I've been getting a segfault (reproduced on both Ubuntu and OS X) in damerau_levenshtein_distance, called from the python library. Strings being compared were "mylifeoutdoors" and "нахлыст".

Poking around in gdb, it looks like the unicode characters cause a bad lookup in the "da" array. If the Cyrillic characters are out of scope for this library, would you be opposed to a change to detect out of bounds code points?

Jellyfish version: 0.5.3

Stack trace:
#0  0x00007feea2c5a340 in damerau_levenshtein_distance (s1=0x7fee9aeee630, s2=0x7fee9aea3eb0, len1=14, len2=7)
    at cjellyfish/damerau_levenshtein.c:58
        infinite = 21
        cols = 9
        i = 1
        j = 7
        i1 = 140662777395312
        j1 = 0
        db = 0
        d1 = 7
        d2 = 7
        d3 = 8
        d4 = <error reading variable d4 (Cannot access memory at address 0x23fb1b90e40100)>
        result = <optimized out>
        dist = 0x18c2180
        da = 0x1c7c510
#1  0x00007feea2c597b6 in jellyfish_damerau_levenshtein_distance (self=<optimized out>, args=<optimized out>)
    at cjellyfish/jellyfishmodule.c:156
        s1 = 0x7fee9aeee630
        s2 = 0x7fee9aea3eb0
        len1 = 14
        len2 = 7
        result = <optimized out>

**Comment by jamesturk** [comment]
thanks for this report, for now the simplest thing would probably be bounds testing, so I'd definitely appreciate a PR w/ this test if you have time

the Python version doesn't have the same restrictions (by virtue of using a dict instead of a fixed sized array), which makes me think it'd be good to find some time to rewrite the C version to not have this restriction either, but I'd gladly accept a fix that just raised an error until I can find time to think through an implementation that allows non-ASCII characters

**Comment by tsellon** [comment]
I'll look into adding some bounds testing today and send a pull request your way.

**Comment by tsellon** [comment]
For tracking purposes, here's a link to the pull request: https://github.com/jamesturk/cjellyfish/pull/1

**Comment by jamesturk** [comment]
thanks! I made a small tweak to the C that raises a ValueError instead and just added a special test for this behavior

**Comment by tsellon** [comment]
Great! Do you know when this could get incorporated into a point release?

**Comment by jamesturk** [comment]
working on one now actually!
