### ISSUE TITLE
Damerau-Levensthein distance doesn't work for higher unicode symbols

### ISSUE THREAD

**Issue by kammala** [jamesturk/jellyfish#55]
Damerau-Levenshtein distance can not be calculated via cjellyfish extension if any of two words contains some unicode symbols(e.g. russian letters, some surrogates such as ŭ, etc)

```
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jellyfish.cjellyfish as cjellyfish
>>> import jellyfish._jellyfish as pyjellyfish
>>> pyjellyfish.damerau_levenshtein_distance(u'хлеб', u'пиво')
4
>>> cjellyfish.damerau_levenshtein_distance(u'хлеб', u'пиво')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Encountered unsupported code point in string.
>>> cjellyfish.damerau_levenshtein_distance(u'tets', u'test')
1
>>> 
```

```
$ pip show jellyfish

---
Metadata-Version: 2.0
Name: jellyfish
Version: 0.5.6
```

**Comment by jamesturk** [comment]
Thanks for reporting this & sorry for the inconvenience.  

Right now this boils down to the C implementation of DL needing a dict-like object to track seen characters, before making this library unicode-aware this was limited to 256 characters, and that hasn't been fixed in this function.

https://github.com/jamesturk/cjellyfish/blob/a319d6ae04134f3c2bcd383012afab5645fba503/damerau_levenshtein.c#L20

A few options to consider:
* autodetect unicode chars & fall back to Python version
* fix C version by adding a map-like data structure (honestly seems like overkill for this purpose as a safe version would nearly double the amount of C code, likely introducing other subtle errors)
* use a simpler data structure like a linked list that doesn't have O(1) access time

I'll think through what makes the most sense here.

**Comment by nchammas** [comment]
I am hitting this as well.

> autodetect unicode chars & fall back to Python version

Is this something end-users can do? How would I force Jellyfish to use the Python implementation for Damerau-Levensthein distance in specific circumstances?

**Comment by jamesturk** [comment]
The easiest way would be to just use the Python version if you know you're
going to need it.


from jellyfish._jellyfish import damerau_levenshtein

the _jellyfish module is the Python implementations, all can be imported
that way

**Comment by nchammas** [comment]
Thanks for the tip! Is this mentioned anywhere in the docs? It seems like it should be mentioned in [index.rst](https://github.com/jamesturk/jellyfish/blob/master/docs/index.rst) at least? I can submit a PR for that if you'd like.

**Comment by jamesturk** [comment]
A PR would be great, it is sort of a hack so I hadn't thought to document
it, but given this use case it makes sense to note.

Thanks

**Comment by almcleanuk** [comment]
In my use case the vast majority of inputs can be processed by the C implementation, so my approach is to use the C implementation,  falling back on the Python implementation only when necessary.

```python
import jellyfish
import jellyfish._jellyfish as py_jellyfish

def damerau_levenshtein_distance(a, b):
    try:
        return jellyfish.damerau_levenshtein_distance(a, b)
    except ValueError:
        logger.debug('Falling back on Python implementation of damerau_levenshtein_distance(%r, %r)', a, b)
        return py_jellyfish.damerau_levenshtein_distance(a, b)
```
Might be worth building this into the library.

**Comment by nchammas** [comment]
For the record, here's another failing test case:

```python
>>> jellyfish.damerau_levenshtein_distance('pahoa', 'pāhoa')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Encountered unsupported code point in string.
```

This is with Jellyfish 0.5.6 on Python 3.6.4.

**Comment by svetlana21** [comment]
Still raises this error :(
`ValueError: Encountered unsupported code point in string.`

**Comment by jamesturk** [comment]
fixed in latest code
